Open Source Places
agrc/metadata-asset-tracking-tool pull request #49
Opened 2024-09-06 03:23 UTC by miriamseely

Current metadata draft for [Utah Open Source](https://gis.utah.gov/products/sgid/society/open-source-places/) places. Let me know what you think!

2024-09-06 05:50 UTC, steveoh commented
I wanted to make sure you are aware of https://gis.utah.gov/blog/2022-03-21-introducing-open-source-places/

2024-09-07 02:42 UTC, miriamseely commented
> I wanted to make sure you are aware of https://gis.utah.gov/blog/2022-03-21-introducing-open-source-places/

I was not aware of this, thank you for sending it my way, there's lots of good stuff in there.

2024-10-03 22:56 UTC, mhchou requested changes
This dataset does not serve a more specific purpose, and the description is great! 
2 changes that I think are worth mentioning:

- The update overwrites the existing data every time. 
- Because of the method mentioned above, some updates could have less data than before, if there are more being removed than being added.

2024-10-04 17:18 UTC, mhchou approved these changes

2024-10-04 17:20 UTC, merged